# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/z/Desktop/project_5/project_5.cache/wt [current_project]
set_property parent.project_path C:/Users/z/Desktop/project_5/project_5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib C:/Users/z/Desktop/project_5/project_5.srcs/sources_1/new/div84.v
synth_design -top div84 -part xc7a35tcsg324-1
write_checkpoint -noxdef div84.dcp
catch { report_utilization -file div84_utilization_synth.rpt -pb div84_utilization_synth.pb }
