# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_5/project_5.cache/wt} [current_project]
set_property parent.project_path {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_5/project_5.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_5/project_5.srcs/sources_1/new/clk4to1.v}
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_5/project_5.srcs/sources_1/new/Snake.v}
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_5/project_5.srcs/sources_1/new/Seg_display.v}
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_5/project_5.srcs/sources_1/new/VGA.v}
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_5/project_5.srcs/sources_1/new/Game_ctrl_unit.v}
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_5/project_5.srcs/sources_1/new/Snake_eating_apple.v}
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_5/project_5.srcs/sources_1/new/Key.v}
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_5/project_5.srcs/sources_1/new/Greedy_Snake.v}
}
read_xdc {{C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_5/project_5.srcs/constrs_1/new/TOP.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_5/project_5.srcs/constrs_1/new/TOP.xdc}}]

synth_design -top Greedy_Snake -part xc7a35tcsg324-1
write_checkpoint -noxdef Greedy_Snake.dcp
catch { report_utilization -file Greedy_Snake_utilization_synth.rpt -pb Greedy_Snake_utilization_synth.pb }
