# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/loadsranm/loadsranm.cache/wt [current_project]
set_property parent.project_path D:/loadsranm/loadsranm.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  D:/loadsranm/loadsranm.srcs/sources_1/new/sramW.v
  D:/loadsranm/loadsranm.srcs/sources_1/new/xiaodou.v
  D:/loadsranm/loadsranm.srcs/sources_1/new/segMsg.v
  D:/loadsranm/loadsranm.srcs/sources_1/new/GPU.v
  D:/loadsranm/loadsranm.srcs/sources_1/new/clkDiv.v
  D:/loadsranm/loadsranm.srcs/sources_1/imports/new/loadsram.v
}
read_xdc D:/loadsranm/loadsranm.srcs/constrs_1/new/guanjiao.xdc
set_property used_in_implementation false [get_files D:/loadsranm/loadsranm.srcs/constrs_1/new/guanjiao.xdc]

synth_design -top loadsram -part xc7a35tcsg324-1
write_checkpoint -noxdef loadsram.dcp
catch { report_utilization -file loadsram_utilization_synth.rpt -pb loadsram_utilization_synth.pb }
