# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_1/project_1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_1/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_1/project_1.srcs/sources_1/new/segMsg2.v}
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_1/project_1.srcs/sources_1/new/GPU.v}
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_1/project_1.srcs/sources_1/new/segMsg1.v}
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_1/project_1.srcs/sources_1/new/dataRead.v}
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_1/project_1.srcs/sources_1/new/clkDiv.v}
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_1/project_1.srcs/sources_1/new/catchPress.v}
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_1/project_1.srcs/sources_1/new/dataShow.v}
  {C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_1/project_1.srcs/sources_1/new/top.v}
}
read_xdc {{C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_1/project_1.srcs/constrs_1/new/scroll.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/zjton/Documents/Tencent Files/2229418979/FileRecv/project_1/project_1.srcs/constrs_1/new/scroll.xdc}}]

synth_design -top top -part xc7a35tcsg324-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
